export {
  THUMB_BASE, FULL_BASE, CODE_FIXES,
  TYPE_NAMES, STAR_NAMES, ATTR_NAMES,
  ATTR_COLORS, TYPE_IMAGES, ATTR_IMAGES, TYPE_COLORS,
  FIELD_BOOSTS, atkColor,
  GUARDIAN_STAR_SYMBOLS, GUARDIAN_STAR_STRONG, GUARDIAN_STAR_WEAK, GUARDIAN_STAR_COLORS,
} from './games/fm/constants'
